py_test(
    name = "test_helper",
    srcs = ["test_helper.py"],
    deps = [
        "//lib:helper_lib",
    ],
    visibility = ["//visibility:public"],
)

py_test(
    name = "test_performance",
    srcs = ["test_performance.py"],
    deps = [
        "//lib:helper_lib",
    ],
)